title: My blog
description: >- 
  I always try to learn things around graphics, IT, math and physics.
baseurl: "/"
url: "https://philae-ael.github.io"

author:
  name: Leathe

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: katex

remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-katex

google_analytics: G-GQ8G5HXWYG
minima:
  skin: auto
  social_links:
   - { platform: github,  user_url: "https://github.com/philae-ael/" }
   - { platform: bluesky, user_url: "https://bsky.app/profile/leathe.dev" }
