title: My blog
description: >- 
  I always try to learn things around graphics, IT, math and physics.
baseurl: "/"
url: "https://blog.leathe.dev"

author:
  name: Leathe

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  math_engine: katex

remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-katex
- jekyll-scholar

collections:
  articles:
    output: true
    permalink: /:collection/:path

exclude:
  - update-biblio.sh

feed:
  path: "/feed.xml"
  collections:
    articles:
      path: "/feed.xml"
    posts: # workaround, we can't remove this collection
      path: "_feed.xml"

minima:
  skin: auto
  social_links:
   - { platform: github,  user_url: "https://github.com/philae-ael/" }
   - { platform: bluesky, user_url: "https://bsky.app/profile/leathe.dev" }
